image: artifactory.f5net.com/dockerhub-remote/centos:7

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_COMMIT_TAG'

stages:
  - build

flake8:
  tags:
    - cm-official-docker-executor
  stage: build
  before_script:
    - yum --enablerepo=extras install -y epel-release
    - yum install -y python-flake8
  script:
    - flake8 f5_endpoint_agent
