image: artifactory.f5net.com/dockerhub-remote/centos:7

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_COMMIT_TAG'

stages:
  - build

flake8:
  tags:
    - cm-official-docker-executor
  stage: build
  before_script:
    - yum --enablerepo=extras install -y epel-release
    - yum install -y python-flake8
  script:
    - flake8 f5_endpoint_agent

# build-agent:
#   services:
#     - docker
#   tags:
#     - cm-official-docker-executor
#   stage: build
#   artifacts:
#     paths:
#       - dist/
#   before_script:
#     - yum --enablerepo=extras install -y epel-release
#     - yum install -y rpm-build python-pip python-setuptools
#   script:
#     - python -m pip install pip==19.0.3
#     - python f5-endpoint-agent-dist/scripts/universal_truth.py
#     - echo "setup.cfg:"
#     - cat setup.cfg
#     - f5-endpoint-agent-dist/scripts/package_agent.sh "redhat" "7"
