sudo: false
language: python
python:
    - '2.7'
before_install:
    - git config --global user.email "OpenStack_TravisCI@f5.com"
    - git config --global user.name "Travis F5 Openstack"
install:
    - pip install hacking pytest pytest-cov .
    - pip install -r requirements.txt
script:
    - flake8 f5_endpoint_agent
    - py.test --cov --ignore=test/
